In [32]:
import pandas as pd

In [33]:
import pandas as pd

df = pd.DataFrame(
    [
        (1, "1900-01-01", "a"),
        (2, "1900-01-01", "b")
     ],
columns=["id", "date", "val"]
).astype({"id": "int64[pyarrow]", "date": "timestamp[ns][pyarrow]", "val":"string[pyarrow]"})

df = df.set_index(["id", "date"])

idx_val = df.index[0]

idx_val in df.index # will show True

df.index.difference([idx_val]) # The two elements are still present in the dataframe

MultiIndex([(1, 1900-01-01 00:00:00),
            (2, 1900-01-01 00:00:00)],
           names=['id', 'date'])

In [34]:
df

                       val
id date
1  1900-01-01 00:00:00   a
2  1900-01-01 00:00:00   b

In [35]:
import pandas as pd

df = pd.DataFrame(
    [
        (1, "1900-01-01", "a"),
        (2, "1900-01-01", "b")
     ],
columns=["id", "date", "val"]
).astype({"id": "int64[pyarrow]", "date": "datetime64[ns]", "val":"string[pyarrow]"})

df = df.set_index(["id", "date"])

idx_val = df.index[0]

idx_val in df.index # will show True

df.index.difference([idx_val]) # The two elements are still present in the dataframe

MultiIndex([(2, '1900-01-01')],
           names=['id', 'date'])

In [36]:
df

              val
id date
1  1900-01-01   a
2  1900-01-01   b